import { ProjectV2 } from "@/types/ProjectV2";

export const MOCK_PROJECTS_V2: ProjectV2[] = [
  {
    id: "proj-001",
    externalId: "EXT-696613",
    clientName: "Cartório Mogi-Mirim",
    ticketNumber: "696613",
    systemType: "Orion PRO",
    implantationType: "new",
    tags: ["São Paulo", "Prioritário", "Q4 2025"],
    priority: "critical",
    projectType: "new",

    healthScore: "warning",
    globalStatus: "in-progress",
    overallProgress: 35,

    description: "Implantação completa do Orion PRO para cartório de Mogi-Mirim com customizações específicas.",
    specialConsiderations: "Cliente requer customização de módulo de Protesto",
    contractValue: 85000,
    paymentMethod: "installments",

    projectLeader: "Bruno Fernandes",
    clientPrimaryContact: "João Silva - Gerente",
    clientEmail: "joao@cartoriomm.com.br",
    clientPhone: "+55 19 98765-4321",
    responsibleInfra: "João Infra",
    responsibleAdherence: "Alex Silva",
    responsibleConversion: "Maria Conversão",
    responsibleImplementation: "Pedro Implantação",
    responsiblePost: "Ana Pós-Impl",

    createdAt: new Date("2025-11-01"),
    startDatePlanned: new Date("2025-11-10"),
    endDatePlanned: new Date("2026-02-15"),
    startDateActual: new Date("2025-11-12"),
    nextFollowUpDate: new Date("2025-11-26"),
    lastUpdatedAt: new Date("2025-11-25T14:30:00"),
    lastUpdatedBy: "Alex Silva",

    stages: {
      infra: {
        status: "done",
        responsible: "João Infra",
        startDate: new Date("2025-11-01"),
        endDate: new Date("2025-11-10"),
        serverInUse: "2008 Server",
        serverNeeded: "Windows 2022 / 8GB RAM / SSD",
        approvedByInfra: true,
        technicalNotes: "Upgrade completo realizado com sucesso",
        observations: "Servidor configurado e testado",
        lastUpdatedAt: new Date("2025-11-10T16:45:00"),
        lastUpdatedBy: "João Infra",
      },
      adherence: {
        status: "in-progress",
        responsible: "Alex Silva",
        startDate: new Date("2025-11-15"),
        hasProductGap: true,
        gapDescription: "Módulo de Protesto não presente na versão padrão",
        devTicket: "DEV-1234",
        devEstimatedDate: new Date("2025-12-02"),
        gapPriority: "high",
        analysisComplete: false,
        conformityStandards: "Verificação de módulos customizados realizadas",
        observations: "Gap encontrado em Protesto, em desenvolvimento",
        lastUpdatedAt: new Date("2025-11-18T15:00:00"),
        lastUpdatedBy: "Alex Silva",
      },
      environment: {
        status: "todo",
        approvedByInfra: false,
        testAvailable: false,
      },
      conversion: {
        status: "todo",
        homologationComplete: false,
      },
      implementation: {
        status: "todo",
      },
      post: {
        status: "todo",
        followupNeeded: false,
      },
    },

    isDeleted: false,
    isArchived: false,

    customFields: {
      responsavel_comercial: "Carlos Vendas",
      industry_type: "Cartório",
    },
  },
  {
    id: "proj-002",
    clientName: "Cartório Itu",
    ticketNumber: "697001",
    systemType: "Orion TN",
    implantationType: "migration_siplan",
    tags: ["São Paulo", "Migração"],
    priority: "high",
    projectType: "migration",

    healthScore: "ok",
    globalStatus: "in-progress",
    overallProgress: 60,

    description: "Migração do sistema Siplan legado para Orion TN",
    projectLeader: "Bruno Fernandes",
    clientPrimaryContact: "Maria Santos",
    responsibleInfra: "João Infra",
    responsibleAdherence: "Pedro Análise",
    responsibleConversion: "Maria Conversão",

    createdAt: new Date("2025-10-15"),
    startDatePlanned: new Date("2025-10-20"),
    endDatePlanned: new Date("2026-01-10"),
    startDateActual: new Date("2025-10-22"),
    nextFollowUpDate: new Date("2025-11-27"),
    lastUpdatedAt: new Date("2025-11-24T09:15:00"),
    lastUpdatedBy: "Pedro Análise",

    stages: {
      infra: {
        status: "done",
        responsible: "João Infra",
        startDate: new Date("2025-10-15"),
        endDate: new Date("2025-10-22"),
        approvedByInfra: true,
        observations: "Infraestrutura aprovada",
      },
      adherence: {
        status: "done",
        responsible: "Pedro Análise",
        startDate: new Date("2025-10-23"),
        endDate: new Date("2025-11-05"),
        hasProductGap: false,
        analysisComplete: true,
        observations: "Análise concluída sem gaps",
      },
      environment: {
        status: "done",
        responsible: "João Infra",
        startDate: new Date("2025-11-06"),
        endDate: new Date("2025-11-12"),
        osVersion: "Windows Server 2022",
        approvedByInfra: true,
        testAvailable: true,
        observations: "Ambiente preparado e testado",
      },
      conversion: {
        status: "in-progress",
        responsible: "Maria Conversão",
        startDate: new Date("2025-11-13"),
        sourceSystem: "Siplan Legacy",
        complexity: "high",
        recordCount: 150000,
        dataVolumeGb: 25,
        homologationComplete: false,
        observations: "Conversão em andamento",
      },
      implementation: {
        status: "todo",
      },
      post: {
        status: "todo",
        followupNeeded: false,
      },
    },

    isDeleted: false,
    isArchived: false,
  },
  {
    id: "proj-003",
    clientName: "Cartório Campinas Centro",
    ticketNumber: "698550",
    systemType: "Orion REG",
    implantationType: "new",
    tags: ["São Paulo", "Grande Porte"],
    priority: "normal",
    projectType: "new",

    healthScore: "critical",
    globalStatus: "blocked",
    overallProgress: 15,

    description: "Nova implantação Orion REG para cartório de grande porte",
    specialConsiderations: "Cliente possui sistemas legados complexos",
    projectLeader: "Bruno Fernandes",
    clientPrimaryContact: "Roberto Lima",
    clientEmail: "roberto@cartoriocampinas.com.br",
    responsibleInfra: "João Infra",

    createdAt: new Date("2025-11-05"),
    startDatePlanned: new Date("2025-11-12"),
    endDatePlanned: new Date("2026-03-20"),
    nextFollowUpDate: new Date("2025-11-20"),
    lastUpdatedAt: new Date("2025-11-18T11:00:00"),
    lastUpdatedBy: "João Infra",

    stages: {
      infra: {
        status: "blocked",
        responsible: "João Infra",
        startDate: new Date("2025-11-05"),
        blockingReason: "client-access",
        serverNeeded: "Windows 2022 / 16GB RAM / SSD 500GB",
        approvedByInfra: false,
        observations: "Aguardando cliente disponibilizar acesso ao ambiente",
        lastUpdatedAt: new Date("2025-11-18T11:00:00"),
        lastUpdatedBy: "João Infra",
      },
      adherence: {
        status: "todo",
        hasProductGap: false,
        analysisComplete: false,
      },
      environment: {
        status: "todo",
        approvedByInfra: false,
        testAvailable: false,
      },
      conversion: {
        status: "todo",
        homologationComplete: false,
      },
      implementation: {
        status: "todo",
      },
      post: {
        status: "todo",
        followupNeeded: false,
      },
    },

    isDeleted: false,
    isArchived: false,
  },
];
