import { Project, User, ProjectStatus, SystemType, UserRole } from "@/types/project";

export const MOCK_USERS: User[] = [
  {
    id: "user-bruno",
    name: "Bruno Fernandes",
    email: "bruno@siplan.com.br",
    role: UserRole.ADMIN,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bruno",
    createdAt: new Date("2025-01-01"),
  },
  {
    id: "user-alex",
    name: "Alex Silva",
    email: "alex@siplan.com.br",
    role: UserRole.ANALYST,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    createdAt: new Date("2025-01-05"),
  },
  {
    id: "user-joao",
    name: "João Infra",
    email: "joao@siplan.com.br",
    role: UserRole.ANALYST,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Joao",
    createdAt: new Date("2025-01-10"),
  },
  {
    id: "user-maria",
    name: "Maria Conversão",
    email: "maria@siplan.com.br",
    role: UserRole.ANALYST,
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Maria",
    createdAt: new Date("2025-01-15"),
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-001",
    clientName: "Mogi-Mirim",
    ticketNumber: "696613",
    systemType: SystemType.ORION_PRO,
    projectLeader: "user-bruno",
    createdAt: new Date("2025-11-01"),
    updatedAt: new Date("2025-11-18"),
    lastUpdateBy: "user-alex",
    nextFollowUpDate: new Date("2025-11-25"),
    stages: {
      infra: {
        status: ProjectStatus.DONE,
        responsible: "user-joao",
        startDate: new Date("2025-11-01"),
        endDate: new Date("2025-11-10"),
        observations: "Servidor configurado, Windows 2022 instalado.",
      },
      adherence: {
        status: ProjectStatus.IN_PROGRESS,
        responsible: "user-alex",
        startDate: new Date("2025-11-15"),
        hasProductGap: true,
        devTicket: "DEV-1234",
        devEstimatedDate: new Date("2025-12-02"),
        observations: "Encontrado gap em módulo de Protesto. Dev em andamento.",
      },
      environment: {
        status: ProjectStatus.TODO,
        responsible: "",
        osVersion: "Windows 2022",
        approvedByInfra: true,
      },
      conversion: {
        status: ProjectStatus.TODO,
        responsible: "user-maria",
        sourceSystem: "Argon",
      },
      implementation: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
      post: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
    },
    timeline: [
      {
        id: "evt-001-1",
        type: "auto",
        author: "system",
        message: "Projeto criado",
        timestamp: new Date("2025-11-01T08:00:00"),
      },
      {
        id: "evt-001-2",
        type: "comment",
        author: "user-alex",
        message: "Análise iniciada. Encontrado gap em módulo de Protesto não presente na versão atual do Orion.",
        timestamp: new Date("2025-11-15T14:30:00"),
      },
      {
        id: "evt-001-3",
        type: "auto",
        author: "system",
        message: "Pendência de Produto ativada. Ticket Dev: DEV-1234",
        timestamp: new Date("2025-11-18T10:00:00"),
      },
    ],
  },
  {
    id: "proj-002",
    clientName: "Itu",
    ticketNumber: "689928",
    systemType: SystemType.ORION_PRO,
    projectLeader: "user-bruno",
    createdAt: new Date("2025-11-05"),
    updatedAt: new Date("2025-11-20"),
    lastUpdateBy: "user-maria",
    nextFollowUpDate: new Date("2025-11-28"),
    stages: {
      infra: {
        status: ProjectStatus.DONE,
        responsible: "user-joao",
        startDate: new Date("2025-11-05"),
        endDate: new Date("2025-11-12"),
      },
      adherence: {
        status: ProjectStatus.DONE,
        responsible: "user-alex",
        startDate: new Date("2025-11-13"),
        endDate: new Date("2025-11-19"),
        hasProductGap: false,
      },
      environment: {
        status: ProjectStatus.DONE,
        responsible: "user-joao",
        realDate: new Date("2025-11-20"),
        osVersion: "Windows 2019",
        approvedByInfra: true,
      },
      conversion: {
        status: ProjectStatus.IN_PROGRESS,
        responsible: "user-maria",
        sourceSystem: "Siplan",
        observations: "Conversão em fase de homologação.",
      },
      implementation: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
      post: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
    },
    timeline: [
      {
        id: "evt-002-1",
        type: "auto",
        author: "system",
        message: "Projeto criado",
        timestamp: new Date("2025-11-05T10:00:00"),
      },
      {
        id: "evt-002-2",
        type: "comment",
        author: "user-maria",
        message: "Conversão de sistema Siplan (conhecida) iniciada. Prazo estimado 2-3 dias.",
        timestamp: new Date("2025-11-20T11:00:00"),
      },
    ],
  },
  {
    id: "proj-003",
    clientName: "Campinas Centro",
    ticketNumber: "701234",
    systemType: SystemType.ORION_TN,
    projectLeader: "user-bruno",
    createdAt: new Date("2025-10-15"),
    updatedAt: new Date("2025-11-01"),
    lastUpdateBy: "user-joao",
    nextFollowUpDate: new Date("2025-11-22"),
    stages: {
      infra: {
        status: ProjectStatus.BLOCKED,
        responsible: "user-joao",
        startDate: new Date("2025-10-16"),
        blockingReason: "Aguardando Compra de Servidor",
        observations: "Cliente precisa aprovar orçamento de hardware.",
      },
      adherence: {
        status: ProjectStatus.TODO,
        responsible: "",
        hasProductGap: false,
      },
      environment: {
        status: ProjectStatus.TODO,
        responsible: "",
        approvedByInfra: false,
      },
      conversion: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
      implementation: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
      post: {
        status: ProjectStatus.TODO,
        responsible: "",
      },
    },
    timeline: [
      {
        id: "evt-003-1",
        type: "auto",
        author: "system",
        message: "Projeto criado",
        timestamp: new Date("2025-10-15T09:00:00"),
      },
      {
        id: "evt-003-2",
        type: "comment",
        author: "user-joao",
        message: "Infraestrutura reprovada. Servidor atual não atende requisitos mínimos.",
        timestamp: new Date("2025-10-20T15:00:00"),
      },
    ],
  },
];
